TASK:
  # TYPE: EQA-rl-v0
  TYPE: ObjectNav-v1
  SENSORS: ['GPS_SENSOR', 'COMPASS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']

ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR", "SEMANTIC_SENSOR", "EQUIRECT_RGB_SENSOR_RESIZED", "EQUIRECT_SEMANTIC_SENSOR_RESIZED"]
    # HEIGHT: 1.25
    RADIUS: 0.1
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
    # ALLOW_SLIDING: True
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    SENSOR_HEIGHT: 1.25
    HFOV: 79
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    SENSOR_HEIGHT: 1.25
    HFOV: 79
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    SENSOR_HEIGHT: 1.25
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 20.0
  EQUIRECT_RGB_SENSOR_RESIZED:
    WIDTH: 1600
    HEIGHT: 400
    HFOV: 90
    VFOV: 360
    # POSITION: [0, 0.88, 0]
    # SENSOR_HEIGHT: 1.25
  EQUIRECT_SEMANTIC_SENSOR_RESIZED:
    WIDTH: 1600
    HEIGHT: 400
    HFOV: 90
    VFOV: 360
    # POSITION: [0, 0.88, 0]
    # SENSOR_HEIGHT: 1.25

DATASET:
  TYPE: MP3DEQA-v1
  SPLIT: train
  DATA_PATH: "data/datasets/eqa/mp3d/v1/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
