TASK:
  # TYPE: EQA-rl-v0
  TYPE: ObjectNav-v1
  # SENSORS: ['QUESTION_SENSOR']
  SENSORS: ['GPS_SENSOR', 'COMPASS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal
  # POSSIBLE_ACTIONS: ['MOVE_FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'STOP', 'ANSWER']
  # POSSIBLE_ACTIONS: ['MOVE_FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'STOP']
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  # MEASUREMENTS: ['EPISODE_INFO', 'DISTANCE_TO_GOAL', 'SUCCESS', 'ANSWER_ACCURACY']
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  # MEASUREMENTS: ['SUCCESS', 'SPL']
  # DISTANCE_TO_GOAL:
  #   DISTANCE_TO: VIEW_POINTS
  SUCCESS:
    SUCCESS_DISTANCE: 0.1

ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ["RGB_SENSOR", "SEMANTIC_SENSOR", "DEPTH_SENSOR", "EQUIRECT_RGB_SENSOR_RESIZED", "EQUIRECT_SEMANTIC_SENSOR_RESIZED"]
    # HEIGHT: 0.88
    # HEIGHT: 1.25
    RADIUS: 0.1
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
    # ALLOW_SLIDING: True
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    SENSOR_HEIGHT: 1.25
    SENSOR_HEIGHT: 0.88
    HFOV: 79
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    SENSOR_HEIGHT: 1.25
    SENSOR_HEIGHT: 0.88
    HFOV: 79
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    # MIN_DEPTH: 0.5
    # MAX_DEPTH: 5.0
    SENSOR_HEIGHT: 1.25
    SENSOR_HEIGHT: 0.88
    HFOV: 79
  EQUIRECT_RGB_SENSOR_RESIZED:
    WIDTH: 1600
    HEIGHT: 400
    HFOV: 90
    VFOV: 360
    # POSITION: [0, 0.88, 0]
    # SENSOR_HEIGHT: 1.25
    SENSOR_HEIGHT: 0.88
  EQUIRECT_SEMANTIC_SENSOR_RESIZED:
    WIDTH: 1600
    HEIGHT: 400
    HFOV: 90
    VFOV: 360
    # POSITION: [0, 0.88, 0]
    # SENSOR_HEIGHT: 1.25
    SENSOR_HEIGHT: 0.88

DATASET:
  TYPE: MP3DEQA-v1
  SPLIT: train
  DATA_PATH: "data/datasets/eqa/scannet/v1/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/scannet"
  # SCENES_DIR: "/home/dbi-data7/daichi.azuma/workspace/Data/ScanNet_All/scans/"
